### ISSUE TITLE
how to run the programs on GPU

### ISSUE THREAD

**Issue by WilliamWangPeng** [hengdashi/cuda_gcn#6]
Dear author,  
    It's an honor to write a letter here,  I use   
# $./cuda_gcn cora    
to run the programs, but the error shows here , do you know why ?  

![image](https://user-images.githubusercontent.com/51076736/142599737-503551a8-68a7-4a36-bc8f-73734bc73609.png)  

thank you  
best regards  
William

**Comment by hengdashi** [comment]
Hi,

sorry for the late response. You can simply unzip the data.tgz file and rerun the command.
